const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getStatus: () => ipcRenderer.invoke('get-status'),
  setSecret: (name, value) => ipcRenderer.invoke('set-secret', name, value),
  setSetting: (name, value) => ipcRenderer.invoke('set-setting', name, value),
  selectWorkspace: () => ipcRenderer.invoke('select-workspace'),
  selectMediaDir: () => ipcRenderer.invoke('select-media-dir'),
  resetMediaDir: () => ipcRenderer.invoke('reset-media-dir'),
  showWorkspace: () => ipcRenderer.invoke('show-workspace'),
  showPath: (target) => ipcRenderer.invoke('show-path', target),
  openInObsidian: (target) => ipcRenderer.invoke('open-in-obsidian', target),
  selectScreenpipe: () => ipcRenderer.invoke('select-screenpipe'),
  clearScreenpipe: () => ipcRenderer.invoke('clear-screenpipe'),
  selectGoogleClient: () => ipcRenderer.invoke('select-google-client'),
  googleConnect: () => ipcRenderer.invoke('google-connect'),
  googleDisconnect: (id) => ipcRenderer.invoke('google-disconnect', id),
  requestMedia: () => ipcRenderer.invoke('request-media'),
  requestMicrophone: () => ipcRenderer.invoke('request-microphone'),
  requestCamera: () => ipcRenderer.invoke('request-camera'),
  detectKeys: () => ipcRenderer.invoke('detect-keys'),
  useDetectedKey: (id) => ipcRenderer.invoke('use-detected-key', id),
  useAnthropicProfile: () => ipcRenderer.invoke('use-anthropic-profile'),
  onePasswordList: (vendor) => ipcRenderer.invoke('onepassword-list', vendor),
  onePasswordImport: (vendor, itemId) => ipcRenderer.invoke('onepassword-import', vendor, itemId),
  onePasswordRefresh: (vendor) => ipcRenderer.invoke('onepassword-refresh', vendor),
  importEnvFile: () => ipcRenderer.invoke('import-env-file'),
  clipboardKey: (vendor) => ipcRenderer.invoke('clipboard-key', vendor),
  dismissGoogleSuggestion: () => ipcRenderer.invoke('dismiss-google-suggestion'),
  forgetEverything: () => ipcRenderer.invoke('forget-everything'),
  openPrivacySettings: (kind) => ipcRenderer.invoke('open-privacy-settings', kind),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  completeWizard: () => ipcRenderer.invoke('complete-wizard'),
  openApp: () => ipcRenderer.invoke('open-app'),
  openSettings: (focus) => ipcRenderer.invoke('open-settings', focus),
  quitApp: () => ipcRenderer.send('quit-app')
});
